apiVersion: clusterop.isim.dev/v1alpha1
kind: KubeletUpgrade
metadata:
  name: replace-nodes-strict
spec:
  failurePolicy: strict
  maxUnavailable: 1
  schedule: "@weekly"
  selector:
    matchExpressions:
    - key: clusterop.isim.dev/kubelet-upgrade
      operator: In
      values: ["replace-nodes-strict"]
  strategy: replace
