apiVersion: clusterop.isim.dev
kind: KubeletUpgrade
metadata:
  name: replace-nodes-ignore
spec:
  failurePolicy: ignore
  maxUnavailable: 1
  schedule: "0 0 * * 0"
  selector:
    matchLabels:
      clusterop.isim.dev/kubelet-upgrade: replace-nodes-ignore
  strategy: replace
