apiVersion: clusterop.isim.dev/v1alpha1
kind: KubeletUpgrade
metadata:
  name: retain-nodes-strict
spec:
  failurePolicy: strict
  maxUnavailable: 1
  schedule: "0 0 * * 0"
  selector:
    matchLabels:
      clusterop.isim.dev/kubelet-upgrade: retain-nodes-strict
  strategy: retain
